addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: b80fb4d5-0b7c-4e92-bc69-58b6f0b7a70c
jdk: [oraclejdk8]
language: java
script: [mvn install, ./df-build.sh]
sudo: 'false'
# Modified by Insights Service at 2016-05-05 13:16:01.977643
